apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: nginx
    image: zzoks/nginx-static:latest
    ports:
    - containerPort: 80

